name: 'Set up build dependencies'
description: 'Set up node, maven dependencies'
inputs:
  node-version:
    description: 'The required node version'
    required: true
    default: 16.14.0
  java-version:
    description: 'The required java version'
    required: true
    default: 11
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
    - name: Install node.js packages
      run: npm ci   
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ inputs.java-version }}
    - name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-   
         