name: Application CI
on: [push, pull_request]

env:
  NODE_VERSION: 16.14.0
  SPRING_OUTPUT_ANSI_ENABLED: DETECT
  SPRING_JPA_SHOW_SQL: false
  JHI_DISABLE_WEBPACK_LOGS: true

jobs:
  snyk-test:
    name: Run Snyk to check for vulnerabilities
    runs-on: ubuntu-latest
    timeout-minutes: 40
    
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-dependencies
      
      - uses: snyk/actions/maven-3-jdk-11@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif  

  backend-test:   
    name: Backend test
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-dependencies
      - name: Run backend test
        run: |
          chmod +x mvnw
          npm run ci:backend:test

  frontend-test:        
    name: Frontend test
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-dependencies
      - name: Run frontend test
        run: npm run ci:frontend:test

  sonar-scan:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-dependencies
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar  
        
      - name: Sonar scan 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   
        run: |
          if [ ! -z "$SONAR_TOKEN" ]; then
              mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=JoseSunoj_Diss22-Store
          else
              echo No SONAR_TOKEN, skipping...
          fi  
     # - name: Package application
      #  run: npm run java:jar:prod
      #- name: Build and publish docker image
       # if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))
       # run: |
        #  GIT_TAG=:${GITHUB_REF#refs/tags/}
         # DOCKER_TAG=${GIT_TAG#:refs/heads/main}
          #./mvnw -ntp jib -Djib.to.image=l00162972/diss22-store${DOCKER_TAG} -Djib.to.auth.username="${{ secrets.DOCKER_USERNAME }}" -Djib.to.auth.password="${{ secrets.DOCKER_PASSWORD }}" -Pprod
